ARG NODE_VERSION=24.13.0
FROM node:${NODE_VERSION}-slim AS base

WORKDIR /app


FROM base AS prepare

RUN npm install -g turbo
COPY ./apps/realtime/out ./out


FROM base AS builder

# copy package*.json struture
COPY --from=prepare /app/out/json/ .
RUN npm ci

# copy all files except node_module and builds
COPY --from=prepare /app/out/full/ .
RUN npm run build --filter=@repo/shared-types


FROM base AS runner

COPY --from=builder /app .

RUN apt-get update \
 && apt-get install -y --no-install-recommends curl ca-certificates \
 && curl -sSL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz \
  | tar -xz -C /usr/local/bin \
 && apt-get purge -y curl && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

CMD ["npm", "run", "dev", "--workspace", "apps/realtime"]
